project:
  type: website

website:
  title: "Isselmou Oumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
  favicon: "images/favicon-32x32.png"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

execute:
  freeze: auto
